In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'data/DataSet_w_NA (1).xlsx'

In [3]:
df = pd.read_excel(path, sheet_name="Испорченные факты")
df.head()

,Номер заказа,Возврат,Дата заказа,Дата отправки,Режим отправки,Факты.Контрагент ID,Факты.Товар ID,"Продажи, руб","Продажи, шт",Скидка,Маржинальная прибыль,Повторение заказа,Повторение контрагента,Повторение товара
0,2014-100279,Нет,2015-09-10 00:00:00,2015-09-14 00:00:00,Стандарт,CLNT0000422,PROD0000870,11190.0,2.0,0.0,5371.20,1,7,3
1,2014-100293,Нет,2015-09-14 00:00:00,2015-09-18 00:00:00,Стандарт,CLNT0000784,PROD0000646,45528.0,6.0,0.2,15934.80,1,4,8
2,2014-100328,Нет,2015-07-28 00:00:00,2015-08-03 00:00:00,Стандарт,CLNT0000342,PROD0000187,1964.0,1.0,0.2,662.85,1,4,12
3,2014-100363,Нет,2015-10-08 00:00:00,2015-10-15 00:00:00,Стандарт,CLNT0000146,PROD0001095,1184.0,2.0,0.2,414.40,2,12,7
4,2014-100363,Нет,2015-10-08 00:00:00,2015-10-15 00:00:00,Стандарт,CLNT0000146,PROD0001616,9504.0,3.0,0.2,3445.20,2,12,3

In [4]:
df.isnull().values.any()

True

In [5]:
df.isna().sum()

Номер заказа                0
Возврат                     0
Дата заказа                 0
Дата отправки               0
Режим отправки              0
Факты.Контрагент ID        90
Факты.Товар ID             51
Продажи, руб              195
Продажи, шт                21
Скидка                      0
Маржинальная прибыль       18
Повторение заказа           0
Повторение контрагента      0
Повторение товара           0
dtype: int64

In [6]:
df = df.dropna()
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9993 entries, 0 to 10292
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Номер заказа            9993 non-null   object
 1   Возврат                 9993 non-null   object
 2   Дата заказа             9993 non-null   object
 3   Дата отправки           9993 non-null   object
 4   Режим отправки          9993 non-null   object
 5   Факты.Контрагент ID     9993 non-null   object
 6   Факты.Товар ID          9993 non-null   object
 7   Продажи, руб            9993 non-null   float64
 8   Продажи, шт             9993 non-null   float64
 9   Скидка                  9993 non-null   float64
 10  Маржинальная прибыль    9993 non-null   float64
 11  Повторение заказа       9993 non-null   int64
 12  Повторение контрагента  9993 non-null   int64
 13  Повторение товара       9993 non-null   int64
dtypes: float64(4), int64(3), object(7)
memory usage: 1.1+ MB

,Номер заказа,Возврат,Дата заказа,Дата отправки,Режим отправки,Факты.Контрагент ID,Факты.Товар ID,"Продажи, руб","Продажи, шт",Скидка,Маржинальная прибыль,Повторение заказа,Повторение контрагента,Повторение товара
0,2014-100279,Нет,2015-09-10 00:00:00,2015-09-14 00:00:00,Стандарт,CLNT0000422,PROD0000870,11190.0,2.0,0.0,5371.20,1,7,3
1,2014-100293,Нет,2015-09-14 00:00:00,2015-09-18 00:00:00,Стандарт,CLNT0000784,PROD0000646,45528.0,6.0,0.2,15934.80,1,4,8
2,2014-100328,Нет,2015-07-28 00:00:00,2015-08-03 00:00:00,Стандарт,CLNT0000342,PROD0000187,1964.0,1.0,0.2,662.85,1,4,12
3,2014-100363,Нет,2015-10-08 00:00:00,2015-10-15 00:00:00,Стандарт,CLNT0000146,PROD0001095,1184.0,2.0,0.2,414.40,2,12,7
4,2014-100363,Нет,2015-10-08 00:00:00,2015-10-15 00:00:00,Стандарт,CLNT0000146,PROD0001616,9504.0,3.0,0.2,3445.20,2,12,3

In [7]:
df = pd.pivot_table(df, values=['Продажи, руб', 'Продажи, шт','Повторение заказа','Маржинальная прибыль'], index=["Факты.Товар ID"],
                     aggfunc={'Продажи, шт': [np.median, np.sum],
                              'Продажи, руб': np.sum,
                              'Повторение заказа': np.sum,
                              'Маржинальная прибыль': np.sum
                               })
df

               Маржинальная прибыль Повторение заказа Продажи, руб  \
                                sum               sum          sum
Факты.Товар ID
PROD0000001               -28160.70                 6     631978.5
PROD0000002               963721.00                32    5318764.0
PROD0000003                32200.55                18      76755.0
PROD0000004              -266380.65                17    3621384.0
PROD0000005                31874.40                18     150984.0
...                             ...               ...          ...
PROD0001890                18223.65                 3     161988.0
PROD0001891               -82476.90                 6     112468.5
PROD0001892                27680.80                 1      98860.0
PROD0001893              -187496.25                 2     749985.0
PROD0001894                 1837.20                 2      18372.0

               Продажи, шт
                    median   sum
Факты.Товар ID
PROD0000001            2.5  12.0
PROD0000002            3.5  51.0
PROD0000003            2.0  23.0
PROD0000004            4.0  29.0
PROD0000005            5.0  24.0
...                    ...   ...
PROD0001890            3.0   3.0
PROD0001891            3.0   3.0
PROD0001892            4.0   4.0
PROD0001893            5.0   5.0
PROD0001894            3.0   3.0

[1862 rows x 5 columns]

In [8]:
newname = df.columns.map('_'.join)
df.columns = newname
df=df.reset_index()
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum"
0,PROD0000001,-28160.70,6,631978.5,2.5,12.0
1,PROD0000002,963721.00,32,5318764.0,3.5,51.0
2,PROD0000003,32200.55,18,76755.0,2.0,23.0
3,PROD0000004,-266380.65,17,3621384.0,4.0,29.0
4,PROD0000005,31874.40,18,150984.0,5.0,24.0
...,...,...,...,...,...,...
1857,PROD0001890,18223.65,3,161988.0,3.0,3.0
1858,PROD0001891,-82476.90,6,112468.5,3.0,3.0
1859,PROD0001892,27680.80,1,98860.0,4.0,4.0
1860,PROD0001893,-187496.25,2,749985.0,5.0,5.0
1861,PROD0001894,1837.20,2,18372.0,3.0,3.0

In [9]:
total_sale=df['Продажи, руб_sum'].sum()
df['Доля']=df['Продажи, руб_sum']/total_sale * 100
df = df.sort_values(by=('Продажи, руб_sum'), ascending=False)
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170
1176,PROD0001187,1.116753e+06,33,9911739.5,3.0,37.0,0.863046
...,...,...,...,...,...,...,...
1838,PROD0001871,1.578500e+03,1,3850.0,2.0,2.0,0.000335
1854,PROD0001887,1.193400e+03,1,3536.0,2.0,2.0,0.000308
1747,PROD0001779,1.555200e+03,3,3240.0,1.0,1.0,0.000282
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071

In [10]:
df = df.assign(sum_d=df['Доля'].cumsum())
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843
1176,PROD0001187,1.116753e+06,33,9911739.5,3.0,37.0,0.863046,6.677889
...,...,...,...,...,...,...,...,...
1838,PROD0001871,1.578500e+03,1,3850.0,2.0,2.0,0.000335,99.999089
1854,PROD0001887,1.193400e+03,1,3536.0,2.0,2.0,0.000308,99.999396
1747,PROD0001779,1.555200e+03,3,3240.0,1.0,1.0,0.000282,99.999679
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000

In [11]:
df = df.assign(ABC='B')
df.loc[(df['sum_d'] <= 80.), 'ABC'] = 'A'
df.loc[(df['sum_d'] > 95.), 'ABC'] = 'C'
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d,ABC
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845,A
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071,A
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673,A
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843,A
1176,PROD0001187,1.116753e+06,33,9911739.5,3.0,37.0,0.863046,6.677889,A
...,...,...,...,...,...,...,...,...,...
1838,PROD0001871,1.578500e+03,1,3850.0,2.0,2.0,0.000335,99.999089,C
1854,PROD0001887,1.193400e+03,1,3536.0,2.0,2.0,0.000308,99.999396,C
1747,PROD0001779,1.555200e+03,3,3240.0,1.0,1.0,0.000282,99.999679,C
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929,C
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000,C

In [12]:
df['Стоимость, руб'] = df['Продажи, руб_sum']/df['Продажи, шт_sum']
df['Продажи в следующем периоде']= (df['Продажи, шт_sum'] + df['Продажи, шт_median']) *df['Стоимость, руб']
total_sale_next=df['Продажи в следующем периоде'].sum()
df['Доля_будущая']=df['Продажи в следующем периоде']/total_sale_next * 100
df = df.sort_values(by=('Продажи в следующем периоде'), ascending=False)
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d,ABC,"Стоимость, руб",Продажи в следующем периоде,Доля_будущая
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845,A,1.539996e+06,3.695989e+07,2.691941
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673,A,1.886540e+06,2.263848e+07,1.648854
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071,A,4.427965e+05,1.505508e+07,1.096523
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843,A,2.803920e+05,1.233725e+07,0.898572
1629,PROD0001657,2.047488e+06,6,9187447.5,4.0,12.0,0.799980,9.126346,A,7.656206e+05,1.224993e+07,0.892213
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,PROD0001257,1.050000e+03,12,4200.0,2.5,5.0,0.000366,99.997704,C,8.400000e+02,6.300000e+03,0.000459
1108,PROD0001119,2.220000e+02,13,4884.0,1.5,6.0,0.000425,99.996103,C,8.140000e+02,6.105000e+03,0.000445
801,PROD0000808,1.702000e+03,2,4048.0,2.5,5.0,0.000352,99.998056,C,8.096000e+02,6.072000e+03,0.000442
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929,C,1.440000e+03,5.760000e+03,0.000420
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000,C,4.060000e+02,1.624000e+03,0.000118

In [13]:
df=df.assign(sum_d_next=df['Доля_будущая'].cumsum())
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d,ABC,"Стоимость, руб",Продажи в следующем периоде,Доля_будущая,sum_d_next
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845,A,1.539996e+06,3.695989e+07,2.691941,2.691941
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673,A,1.886540e+06,2.263848e+07,1.648854,4.340795
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071,A,4.427965e+05,1.505508e+07,1.096523,5.437318
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843,A,2.803920e+05,1.233725e+07,0.898572,6.335891
1629,PROD0001657,2.047488e+06,6,9187447.5,4.0,12.0,0.799980,9.126346,A,7.656206e+05,1.224993e+07,0.892213,7.228103
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,PROD0001257,1.050000e+03,12,4200.0,2.5,5.0,0.000366,99.997704,C,8.400000e+02,6.300000e+03,0.000459,99.998575
1108,PROD0001119,2.220000e+02,13,4884.0,1.5,6.0,0.000425,99.996103,C,8.140000e+02,6.105000e+03,0.000445,99.999020
801,PROD0000808,1.702000e+03,2,4048.0,2.5,5.0,0.000352,99.998056,C,8.096000e+02,6.072000e+03,0.000442,99.999462
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929,C,1.440000e+03,5.760000e+03,0.000420,99.999882
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000,C,4.060000e+02,1.624000e+03,0.000118,100.000000

In [14]:
df.loc[(df['sum_d_next'] <= 80), 'ABC_next'] = 'A'
df.loc[(df['sum_d_next'] > 80) & (df['sum_d_next'] <= 95), 'ABC_next'] = 'B'
df.loc[(df['sum_d_next'] > 95), 'ABC_next'] = 'C'
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d,ABC,"Стоимость, руб",Продажи в следующем периоде,Доля_будущая,sum_d_next,ABC_next
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845,A,1.539996e+06,3.695989e+07,2.691941,2.691941,A
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673,A,1.886540e+06,2.263848e+07,1.648854,4.340795,A
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071,A,4.427965e+05,1.505508e+07,1.096523,5.437318,A
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843,A,2.803920e+05,1.233725e+07,0.898572,6.335891,A
1629,PROD0001657,2.047488e+06,6,9187447.5,4.0,12.0,0.799980,9.126346,A,7.656206e+05,1.224993e+07,0.892213,7.228103,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,PROD0001257,1.050000e+03,12,4200.0,2.5,5.0,0.000366,99.997704,C,8.400000e+02,6.300000e+03,0.000459,99.998575,C
1108,PROD0001119,2.220000e+02,13,4884.0,1.5,6.0,0.000425,99.996103,C,8.140000e+02,6.105000e+03,0.000445,99.999020,C
801,PROD0000808,1.702000e+03,2,4048.0,2.5,5.0,0.000352,99.998056,C,8.096000e+02,6.072000e+03,0.000442,99.999462,C
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929,C,1.440000e+03,5.760000e+03,0.000420,99.999882,C
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000,C,4.060000e+02,1.624000e+03,0.000118,100.000000,C

In [15]:
df.loc[(df['ABC'] != df['ABC_next']), 'Изменение класса'] = 1
df.loc[(df['ABC'] == df['ABC_next']), 'Изменение класса'] = 0
df['Изменение класса'].sum()

61.0

In [16]:
abc_to_index = dict(zip('ABC', range(len('ABC'))))
abc_to_index

{'A': 0, 'B': 1, 'C': 2}

In [17]:
df['class'] = df['ABC'].map(abc_to_index)
df['class_next'] = df['ABC_next'].map(abc_to_index)
df

,Факты.Товар ID,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median","Продажи, шт_sum",Доля,sum_d,ABC,"Стоимость, руб",Продажи в следующем периоде,Доля_будущая,sum_d_next,ABC_next,Изменение класса,class,class_next
1388,PROD0001406,1.259996e+07,17,30799912.0,4.0,20.0,2.681845,2.681845,A,1.539996e+06,3.695989e+07,2.691941,2.691941,A,0.0,0,0
1411,PROD0001430,-9.055392e+05,7,11319240.0,6.0,6.0,0.985602,4.862673,A,1.886540e+06,2.263848e+07,1.648854,4.340795,A,0.0,0,0
450,PROD0000454,3.876520e+06,23,13726692.0,3.0,31.0,1.195226,3.877071,A,4.427965e+05,1.505508e+07,1.096523,5.437318,A,0.0,0,0
483,PROD0000488,1.746230e-10,15,10935288.0,5.0,39.0,0.952170,5.814843,A,2.803920e+05,1.233725e+07,0.898572,6.335891,A,0.0,0,0
1629,PROD0001657,2.047488e+06,6,9187447.5,4.0,12.0,0.799980,9.126346,A,7.656206e+05,1.224993e+07,0.892213,7.228103,A,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,PROD0001257,1.050000e+03,12,4200.0,2.5,5.0,0.000366,99.997704,C,8.400000e+02,6.300000e+03,0.000459,99.998575,C,0.0,2,2
1108,PROD0001119,2.220000e+02,13,4884.0,1.5,6.0,0.000425,99.996103,C,8.140000e+02,6.105000e+03,0.000445,99.999020,C,0.0,2,2
801,PROD0000808,1.702000e+03,2,4048.0,2.5,5.0,0.000352,99.998056,C,8.096000e+02,6.072000e+03,0.000442,99.999462,C,0.0,2,2
1675,PROD0001703,1.411200e+03,1,2880.0,2.0,2.0,0.000251,99.999929,C,1.440000e+03,5.760000e+03,0.000420,99.999882,C,0.0,2,2
237,PROD0000239,-2.233000e+03,1,812.0,2.0,2.0,0.000071,100.000000,C,4.060000e+02,1.624000e+03,0.000118,100.000000,C,0.0,2,2

In [18]:
from sklearn import model_selection
from sklearn import preprocessing


columns = ['Маржинальная прибыль_sum', 'Повторение заказа_sum', 
       'Продажи, руб_sum', 'Продажи, шт_median', 
       'Доля', 'Стоимость, руб', 'Продажи в следующем периоде']

Y = df['class_next']
X = df[columns]

scaler = preprocessing.MinMaxScaler(feature_range=(0, 10))
scaled_data = scaler.fit_transform(X.loc[:, X.columns == 'Маржинальная прибыль_sum'])
X['Маржинальная прибыль_sum'] =  scaled_data

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2)
X_train

/Users/lllprot/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Маржинальная прибыль_sum,Повторение заказа_sum,"Продажи, руб_sum","Продажи, шт_median",Доля,"Стоимость, руб",Продажи в следующем периоде
1532,2.618568,20,52644.0,2.0,0.004584,2024.769231,5.669354e+04
1461,3.140481,21,6971834.0,6.0,0.607060,178764.974359,8.044424e+06
939,2.612037,2,66930.0,7.0,0.005828,4780.714286,1.003950e+05
755,2.630996,18,105754.0,2.0,0.009208,3916.814815,1.135876e+05
318,2.610553,10,20650.0,2.5,0.001798,1877.272727,2.534318e+04
...,...,...,...,...,...,...,...
1209,2.458004,56,2083442.0,4.5,0.181412,35312.576271,2.242349e+06
734,2.975743,32,3297477.0,3.0,0.287122,82436.925000,3.544788e+06
1640,2.649042,2,393450.0,7.0,0.034259,28103.571429,5.901750e+05
643,2.716105,17,1005426.0,4.0,0.087546,34669.862069,1.144105e+06
239,2.622788,6,441051.0,3.0,0.038404,40095.545455,5.613376e+05

In [19]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)
rfc.score(X_test, Y_test)

1.0

In [20]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, Y_train)
svc.score(X_test, Y_test)

0.9731903485254692

In [21]:
from sklearn.naive_bayes import MultinomialNB


mnb = MultinomialNB()
mnb.fit(X_train, Y_train)
mnb.score(X_test, Y_test)

0.44235924932975873

In [22]:
df.corr().style.background_gradient(cmap='coolwarm')

In [ ]:
# на низкую маржинальность влиеяет низкая класс товара и его доля в общей сумме продаж,
# чем меньше по обороту товар тем ниже маржиналость